author: tex
name: fracturedcosmetics
main: com.fractured.FracturedCore
api-version: 1.20
version: ${project.version}

commands:
  cosmetics:
    aliases: []
  projectiletrail:
    aliases: []
  hit_effect:
    aliases: []
